# version format
version: 0.1.{build}

environment:
  GIT_TRACE: 1
  access_token:
    secure: bDZ9LJ84SWlGw/D3R/q3ADwDslfrLNZLMdH3ZRjdi5xwkGanmjf7DvgN+crc4BU/
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: bdyanCqxWP0hylNYUvdIl8eUlDMhmIsmeFUNxGwnESlEksBZnxcLhaj1lYVuD7LM
  codecov_key:
    secure: P8TyHefSoYBAZk/UMFHNWcfmcjQp0o3X3fP3DMFhTzxXa6yXlA+w8CT69jYfh7n/
  github_email:
    secure: x5ljenzXfYXkzpEu9eX7AQvb3AkFbiXG2NndMzw9Zc4=

skip_commits:
  files:
    - docs\*
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
    - CHANGELOG.md
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - build\
    - DoubleDeploy\
    - tests\

image: Visual Studio 2013

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - ps: . .\build\install.ps1

build_script:
  - ps: . .\build\build.ps1

test_script:
  - ps: . .\build\test.ps1

deploy_script:
  - git config --global core.safecrlf false
  - git config --global credential.helper store
  - ps: Set-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email %github_email%
  - git config --global user.name "Pete Maan"
  - git checkout %APPVEYOR_REPO_BRANCH% -q
  - git add *.psd1
  - git status
  - git commit -s -m "Update Version"
  - git push --porcelain origin %APPVEYOR_REPO_BRANCH%